version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.11.1-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
      - setup_remote_docker
      - run: docker login -u $DOCKER_USERNAME -p $DOCKERPASSWORD
      - run:
          name: "Build docker image and push to dkcoer hub"
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker build -t ohmliveza/dockerproject:latest .
              docker build -t ohmliveza/dockerproject:${CIRCLE_SHA1} .
              docker push ohmliveza/dockerproject:latest
              docker push ohmliveza/dockerproject:${CIRCLE_SHA1}
            elif [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker build -t ohmliveza/dockerproject:latest .
              docker push ohmliveza/dockerproject:latest
            else
              echo "This is ${CIRCLE_BRANCH}"
            fi
       - run:
          name: "Call to rancher to deploy"
          command: |
            docker run --rm -it \
              -e CATTLE_ACCESS_KEY="$CATTLE_ACCESS_KEY" \
              -e CATTLE_SECRET_KEY="$CATTLE_SECRET_KEY" \
              -e CATTLE_URL="$CATTLE_URL" \
              etlweather/gaucho upgrade $RANCHER_EXAMPLE_NODEJS \
              --imageUuid 'docker:ohmliveza/dockerproject:latest' \
              --batch_size 3 --start_first \
              --auto_complete --timeout 600\
              /
      - run: echo Done